# a_tensor_initialization.py

In [17]:
import torch

t1 = torch.Tensor([1, 2, 3], device = 'cpu') #tensor 기본 속성 확인
print(t1.dtype)
print(t1.device)
print(t1.requires_grad)
print(t1.size())
print(t1.shape)

t1_cpu = t1.cpu()
print("#" * 50, 1)

t2 = torch.Tensor([1, 2, 3], device = 'cpu')
print(t2.dtype)
print(t2.device)
print(t2.requires_grad)
print(t2.size())
print(t2.shape)

t2_cpu = t2.cpu()
print("#" * 50, 2)

a1 = torch.tensor(1) # 스칼라
print(a1.shape, a1.ndim)

a2 = torch.tensor([1]) # 벡터(1차원)
print(a2.shape, a2.ndim)

a3 = torch.tensor([1, 2, 3, 4, 5])
print(a3.shape, a3.ndim)

a4 = torch.tensor([[1], [2], [3], [4], [5]]) # 행렬(2차원)
print(a4.shape, a4.ndim)

a5 = torch.tensor([[1, 2], [3, 4], [5, 6]])
print(a5.shape, a5.ndim)

a6 = torch.tensor([[[1], [2]], [[3], [4]], [[5], [6]]]) # 3차원 텐서
print(a6.shape, a6.ndim)

a7 = torch.tensor([
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim)

a8 = torch.tensor([
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print(a8.shape, a8.ndim)

a9 = torch.tensor([ # 5차원 텐서
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim)

a10 = torch.tensor([
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])
print(a10.shape, a10.ndim)

a11 = torch.tensor([
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
])
print(a11.shape, a11.ndim)

#a12 = torch.tensor([
#    [[[1, 2, 3], [4, 5]]],
#    [[[1, 2, 3], [4, 5]]],
#    [[[1, 2, 3], [4, 5]]],
#    [[[1, 2, 3], [4, 5]]],
#])
#print(a12.shape, a12.ndim)

torch.float32
cpu
False
torch.Size([3])
torch.Size([3])
################################################## 1
torch.float32
cpu
False
torch.Size([3])
torch.Size([3])
################################################## 2
torch.Size([]) 0
torch.Size([1]) 1
torch.Size([5]) 1
torch.Size([5, 1]) 2
torch.Size([3, 2]) 2
torch.Size([3, 2, 1]) 3
torch.Size([3, 1, 2, 1]) 4
torch.Size([3, 1, 2, 3]) 4
torch.Size([3, 1, 2, 3, 1]) 5
torch.Size([4, 5]) 2
torch.Size([4, 1, 5]) 3


In [ ]:
a12 해결방법
a12 = torch.tensor([
    [[[1, 2, 3], [4, 5, 0]]],  # 0으로 패딩
    [[[1, 2, 3], [4, 5, 0]]],
    [[[1, 2, 3], [4, 5, 0]]],
    [[[1, 2, 3], [4, 5, 0]]],
])

or

a12 = torch.tensor([
    [[[1, 2, 3], [4, 5, 6]]],  # 모두 길이 3으로
    [[[1, 2, 3], [4, 5, 6]]],
    [[[1, 2, 3], [4, 5, 6]]],
    [[[1, 2, 3], [4, 5, 6]]],
])

or

a12 = torch.tensor([
    [[1, 2], [4, 5]],  # 모두 길이 2로
    [[1, 2], [4, 5]],
    [[1, 2], [4, 5]],
    [[1, 2], [4, 5]],
])

텐서란?
: 다차원 배열의 일반화된 형태

어떨 때 쓰일까?
: 대량 데이터를 효율적으로 처리해야 할 때

# b_tensor_initialization_copy.py

In [2]:
import torch
import numpy as np

l1 = [1, 2, 3]
t1 = torch.Tensor(l1)

l2 = [1, 2, 3]
t2 = torch.Tensor(l2)

l3 = [1, 2, 3]
t3 = torch.as_tensor(l3) # 정수형

l1[0] = 100
l2[0] = 100
l3[0] = 100

print(t1)
print(t2)
print(t3)

print("#" * 100)

tensor([1., 2., 3.])
tensor([1., 2., 3.])
tensor([1, 2, 3])
####################################################################################################


In [ ]:
PyTorch에서 텐서 생성 방식의 차이점을 보여주는 코드

torch.Tensor() 무조건 float32로 변환

# c_tensor_initialization_constant_values.py

In [15]:
import torch

t1 = torch.ones(size = (5,))
t1_like = torch.ones_like(input = t1)
print(t1)
print(t1_like)

t2 = torch.zeros(size = (6,))
t2_like = torch.ones_like(input = t2)
print(t2)
print(t2_like)

t3 = torch.zeros(size = (4,))
t3_like = torch.ones_like(input = t3)
print(t3)
print(t3_like)

t4 = torch.eye(n = 3)
print(t4)

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([1., 1., 1., 1., 1., 1.])
tensor([0., 0., 0., 0.])
tensor([1., 1., 1., 1.])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [ ]:
torch.ones()
: 1로 채워진 텐서 생성

torch.zeros()
: 0으로 채워진 텐서 생성

torch.eye()
: 대각선은 1, 나머지는 0으로 채워진 텐서 생성

torch.ones_like()
: 템플릿 텐서의 모든 속성을 복사하되, 값만 1로 채워진 텐서 생성

# d_tensor_initialization_random_values.py

In [2]:
import torch

t1 = torch.randint(low = 10, high = 20, size = (1, 2)) # 10~19 사이 정수 랜덤
print(t1)

t2 = torch.rand(size = (1, 3)) # 0~1 사이 균등분포
print(t2)

t3 = torch.randn(size = (1, 3)) # 평균 0, 표준편차1 정규분포
print(t3)

t4 = torch.normal(mean = 10.0, std = 1.0, size = (3, 2)) # 평균 10, 표준편차1 정규분포
print(t4)

t5 = torch.linspace(start = 0.0, end = 5.0, steps = 3) # 0부터 5까지 3개 구간으로 등분
print(t5)

t6 = torch.arange(5) # 0부터 4까지 순차적 정수
print(t6)

print("#" * 30)

torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

print()

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[10, 14]])
tensor([[0.6070, 0.5958, 0.9599]])
tensor([[ 0.3042, -0.4315,  1.0217]])
tensor([[11.1650, 10.7828],
        [ 9.4753, 10.0820],
        [ 9.9322,  9.4959]])
tensor([0.0000, 2.5000, 5.0000])
tensor([0, 1, 2, 3, 4])
##############################
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


In [ ]:
torch.manual_seed()
: 제한된 랜덤값 얻음

# e_tensor_type_conversion.py

In [6]:
import torch

a = torch.ones((2, 3)) # 기본값: float32
print(a.dtype)

b = torch.ones((2, 3), dtype = torch.int16) # 16비트 정수로 지정
print(b)

c = torch.rand((2, 3), dtype = torch.float64) * 20 # 64비트 부동소수점
print(c)

d = b.to(torch.int32) # int16 → int32 변환
print(d)

double_d = torch.ones(10, 2, dtype = torch.double) # float32 → float64 변환
short_e = torch.tensor([[1, 2]], dtype = torch.short)

double_d = torch.zeros(10, 2).double() # .double() = float64로 변환
short_e = torch.ones(10, 2).short() # .short() = int16으로 변환

double_d = torch.zeros(10, 2).to(torch.double)
short_e = torch.ones(10, 2).to(dtype = torch.short)

print(double_d.double)
print(short_e.dtype)

double_f = torch.rand(5, dtype = torch.double)
short_g = double_f.to(torch.short)
print((double_f * short_g).dtype)

torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[13.0737,  6.8375,  1.3056],
        [19.1222, 18.1333, 15.8734]], dtype=torch.float64)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
<built-in method double of Tensor object at 0x0000023B5B557980>
torch.int16
torch.float64


In [ ]:
서로 다른 dtype끼리 연산할 때의 결과
-> 더 정밀한 타입으로 자동 변경

float64 × int16 → float64
float32 × int64 → float32
int32 × int16 → int32

# f_tensor_operations.py

In [7]:
import torch

t1 = torch.ones(size = (2, 3))
t2 = torch.ones(size = (2, 3))
t3 = torch.add(t1, t2)
t4 = t1 + t2 # 덧셈
print(t3)
print(t4)

print("#" * 30)

t5 = torch.sub(t1, t2)
t6 = t1 - t2 # 뺼셈
print(t5)
print(t6)

print("#" * 30)

t7 = torch.mul(t1, t2)
t8 = t1 * t2 # 곱셈
print(t7)
print(t8)

print("#" * 30)

t9 = torch.div(t1, t2)
t10 = t1 / t2 # 나눗셈
print(t9)
print(t10)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
##############################
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
##############################
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
##############################
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
pytorch에서도 산술연산자 사용 가능

# g_tensor_operations_mm.py

In [9]:
import torch 

t1 = torch.dot(torch.tensor([2, 3]), torch.tensor([2, 1])) # 벡터 내적
print(t1, t1.size())

t2 = torch.randn(2, 3)
t3 = torch.randn(3, 2)
t4 = torch.mm(t2, t3) # 일반 행렬 곱셈
print(t4, t4.size())

t5 = torch.randn(10, 3, 4)
t6 = torch.randn(10, 4, 3)
t7 = torch.bmm(t5, t6) # 배치 행렬 곱셈
print(t7.size())

tensor(7) torch.Size([])
tensor([[-6.3439,  2.8569],
        [ 0.2075, -1.0269]]) torch.Size([2, 2])
torch.Size([10, 3, 3])


In [ ]:
dot()
: 1차원 벡터끼리만 가능

mm()
: 2차원 행렬끼리만 가능

bmm()
: 3차원 텐서끼리 각 배치별로 독립적으로 행렬 곱셈 수행

# h_tensor_operations_matmul.py

In [11]:
import torch

t1 = torch.randn(3)
t2 = torch.randn(3)
print(torch.matmul(t1, t2).size()) # 벡터 × 벡터 → 내적

t3 = torch.randn(3, 4)
t4 = torch.randn(4)
print(torch.matmul(t3, t4).size()) # 행렬 × 벡터 → 행렬-벡터 곱셈

t5 = torch.randn(10, 3, 4)
t6 = torch.randn(4)
print(torch.matmul(t5, t6).size()) # 배치행렬 × 벡터 → 브로드캐스팅

t7 = torch.randn(10, 3, 4)
t8 = torch.randn(10, 4, 5)
print(torch.matmul(t7, t8).size()) # 배치행렬 × 배치행렬 → 배치 행렬 곱셈

t9 = torch.randn(10, 3, 4)
t10 = torch.randn(4, 5)
print(torch.matmul(t9, t10).size()) # 배치행렬 × 행렬 → 브로드캐스팅

torch.Size([])
torch.Size([3])
torch.Size([10, 3])
torch.Size([10, 3, 5])
torch.Size([10, 3, 5])


In [ ]:
갑자기 든 생각. 행렬끼리 왜 곱하지? 어디서 쓰일 수 있지?
: 신경망에서 핵심 역할, 뉴런의 작동 원리 자체가 행렬곱

# i_tensor_broadcasting.py

In [13]:
import torch

t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(t1 * t2) # 스칼라 브로드캐스팅

print("#" * 50, 1)

t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5])
print(t3 - t4) # 벡터 프로드캐스팅

print("#" * 50, 2)

t5 = torch.tensor([[1., 2.], [3., 4.]])
print(t5 + 2.0)
print(t5 - 2.0)
print(t5 * 2.0)
print(t5 / 2.0)

print("#" * 50, 3)

def normalize(x):
    return x / 255

t6 = torch.randn(3, 28, 28)
print(normalize(t6).size())

print("#" * 50, 4)

t7 = torch.tensor([[1, 2], [0, 3]])
t8 = torch.tensor([[3, 1]])
t9 = torch.tensor([[5], [2]])
t10 = torch.tensor([7])
print(t7 + t8)
print(t7 + t9)
print(t8 + t9)
print(t7 + t10)

print("#" * 50, 5)

t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3, 2)
print(t12.shape)

t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1)
print(t14.shape)

t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)
print(t16.shape)

t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)
print((t17 + t18).size())

print("#" * 50, 6)

t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())

t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())

t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size())

#t25 = torch.empty(5, 2, 4, 1)
#t26 = torch.empty(3, 1, 1)
#print((t25 + t26).size())

print("#" * 50, 7)

t27 = torch.ones(4) * 5
print(t27)

t28 = torch.pow(t27, 2) # 거듭제곱
print(t28)

exp = torch.arange(1., 5.)
a = torch.arange(1., 5.)
t29 = torch.pow(a, exp)
print(t29)

tensor([2., 4., 6.])
################################################## 1
tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])
################################################## 2
tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])
################################################## 3
torch.Size([3, 28, 28])
################################################## 4
tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])
################################################## 5
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([5, 3, 4, 1])
################################################## 6
torch.Size([5, 3, 4, 1])
torch.Size([3, 1, 7])
torch.Size([3, 3, 3])
################################################## 7
tensor([5., 5., 5., 5.])
tensor([25., 25., 25., 25.])
tensor([  1

In [ ]:
브로드캐스팅이란?
크기가 다른 배열(텐서)끼리 연산할 때, 자동으로 크기를 맞춰주는 메커니즘

# j_tensor_indexing_slicing.py

In [18]:
import torch

x = torch.tensor(
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9],
   [10, 11, 12, 13, 14]]
)

print(x[1])
print(x[:, 1])
print(x[1, 2])
print(x[: -1]) # 슬라이싱`

print("#" * 50, 1)

print(x[1:])
print(x[1:, 3:])

print("#" * 50, 2)

y = torch.zeros((6, 6))
y[1:4, 2] = 1
print(y)

print(y[1:4, 1:4])

print("#" * 50, 3)

z = torch.tensor(
  [[1, 2, 3, 4],
   [2, 3, 4, 5],
   [5, 6, 7, 8]]
)

print(z[:2])
print(z[1:, 1:3])
print(z[:, 1:])

z[1:, 1:3] = 0
print(z)

tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
################################################## 1
tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])
################################################## 2
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])
################################################## 3
tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


In [ ]:
슬라이싱은 어떨 때 쓰일까?
: 이미지 처리, 자연어 처리, 데이터 분할, 배치 처리, 신경망 구조 등

# k_tensor_reshaping.py

In [23]:
import torch

t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = t1.view(3, 2)
t3 = t1.reshape(1, 6)
print(t2)
print(t3)

t4 = torch.arange(8).view(2, 4)
t5 = torch.arange(6).view(2, 3)
print(t4)
print(t5)

print("#" * 50, 1)

t6 = torch.tensor([[[1], [2], [3]]])
t7 = t6.squeeze()
t8 = t6.squeeze(0) # 0번째 차원 제거
print(t7)
print(t8)

print("#" * 50, 2)

t9 = torch.tensor([1, 2, 3])
t10 = t9.unsqueeze(1) # 1번째 위치에 차원 추가
print(t10)

t11 = torch.tensor(
  [[1, 2, 3],
   [4, 5, 6]]
)
t12 = t11.unsqueeze(1)
print(t12, t12.shape)

print("#" * 50, 3)

t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t14 = t13.flatten() # 평면화
print(t14)

t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]])
t16 = torch.flatten(t15)
t17 = torch.flatten(t15, start_dim = 1)
print(t16)
print(t17)

print("#" * 50, 4)

t18 = torch.randn(2, 3, 5)
print(t18.shape)
print(torch.permute(t18, (2, 0, 1)).size()) # 차원 순서 바꾸기

t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t20 = torch.permute(t19, dims = (0, 1))
t21 = torch.permute(t19, dims = (1, 0))
print(t20)
print(t21)

t22 = torch.transpose(t19, 0, 1)
print(t22)

t23 = torch.t(t19)
print(t23)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])
################################################## 1
tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])
################################################## 2
tensor([[1],
        [2],
        [3]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])
################################################## 3
tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
################################################## 4
torch.Size([2, 3, 5])
torch.Size([5, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [ ]:
squeeze()
: 크기가 1인 차원 제거

unsqueeze()
: 새로운 차원 추가

flatten()
: 다차원을 1차원으로

permute()
: 차원 순서 변경

# l_tensor_concat.py

In [26]:
import torch

t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])

t4 = torch.cat([t1, t2, t3], dim = 1) # 서로 다른 크기 연결
print(t4.shape)

print("#" * 50, 1)

t5 = torch.arange(0, 3)
t6 = torch.arange(3, 8)
t7 = torch.cat((t5, t6), dim = 0)
print(t7.shape) # 1차원 벡터 연결
print(t7)

print("#" * 50, 2)

t8 = torch.arange(0, 6).reshape(2, 3)
t9 = torch.arange(6, 12).reshape(2, 3)
t10 = torch.cat((t8, t9), dim = 0)
print(t10.size()) # 2차원 행렬 연결
print(t10)

t11 = torch.cat((t8, t9), dim = 1)
print(t11.size())
print(t11)

print("#" * 50, 3)

t12 = torch.arange(0, 6).reshape(2, 3)
t13 = torch.arange(6, 12).reshape(2, 3)
t14 = torch.arange(12, 18).reshape(2, 3)

t15 = torch.cat((t12, t13, t14), dim = 0)
print(t15.size())
print(t15)

t16 = torch.cat((t12, t13, t14), dim = 1)
print(t16.size())
print(t16)

print("#" * 50, 4)

t17 = torch.arange(0, 6).reshape(1, 2, 3)
t18 = torch.arange(6, 12).reshape(1, 2, 3)
t19 = torch.cat((t17, t18), dim = 0)
print(t19.size()) # 3차원 텐서 연결
print(t19)

t20 = torch.cat((t17, t18), dim = 1)
print(t20.size())
print(t20)

t21 = torch.cat((t17, t18), dim = 2)
print(t21.size())
print(t21)

torch.Size([2, 6, 3])
################################################## 1
torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])
################################################## 2
torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])
################################################## 3
torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])
################################################## 4
torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 2, 6])
t

In [ ]:
텐서 합치는 건 어떨 때 쓰이지?
: 배치 데이터 합치기, 피처 결합, 시계열 데이터 확장

# m_tensor_stacking.py

In [27]:
import torch

t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

t3 = torch.stack([t1, t2], dim = 0)
t4 = torch.cat([t1.unsqueeze(dim = 0), t2.unsqueeze(dim = 0)], dim = 0)
print(t3.shape, t3.equal(t4))

t5 = torch.stack([t1, t2], dim = 1)
t6 = torch.cat([t1.unsqueeze(dim = 1), t2.unsqueeze(dim = 1)], dim = 1)
print(t5.shape, t5.equal(t6))

t7 = torch.stack([t1, t2], dim = 2)
t8 = torch.cat([t1.unsqueeze(dim = 2), t2.unsqueeze(dim = 2)], dim = 2)
print(t7.shape, t7.equal(t8))

print("#" * 50, 1)

t9 = torch.arange(0, 3)
t10 = torch.arange(3, 6)
print(t9.size(), t10.size())

t11 = torch.stack((t9, t10), dim = 0)
print(t11.size())
print(t11)

t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim = 0)
print(t11.equal(t12))

t13 = torch.stack((t9, t10), dim = 1)
print(t13.size())
print(t13)

t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim = 1)
print(t13.equal(t14))

torch.Size([2, 2, 3]) True
torch.Size([2, 2, 3]) True
torch.Size([2, 3, 2]) True
################################################## 1
torch.Size([3]) torch.Size([3])
torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])
True
torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])
True


In [ ]:
torch.stack() vs torch.cat()

torch.cat()
: 기존 차원 확장

torch.stack()
: 새로운 차원 생성

# n_tensor_vstack_hstack.py

In [28]:
import torch

t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.vstack((t1, t2))

t4 = torch.tensor([[1], [2], [3]])
t5 = torch.tensor([[4], [5], [6]])
t6 = torch.vstack((t4, t5)) # 세로로 쌓기

t7 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t7.shape)

t8 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t8.shape)

t9 = torch.vstack([t7, t8])
print(t9.shape)
print(t9)

print("#" * 50, 1)

t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])
t12 = torch.hstack((t10, t11))
print(t12)

t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]])
t15 = torch.hstack((t13, t14)) # 세로로 쌓기
print(t15)

t16 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)

t17 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t17.shape)

t18 = torch.hstack([t16, t17])
print(t18.shape)
print(t18)

torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])
################################################## 1
tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])


In [ ]:
torch.vstack()

t1 = [1, 2, 3]     ←── 첫 번째 줄
t2 = [4, 5, 6]     ←── 두 번째 줄

vstack 결과:
[1, 2, 3]  ←── t1
[4, 5, 6]  ←── t2

torch.hstack()

t1 = [1, 2, 3]  |  t2 = [4, 5, 6]
                ↓
hstack 결과: [1, 2, 3, 4, 5, 6]

## 숙제 후기

In [ ]:
지금까지 텐서가 무엇인지, 텐서를 어떻게 만드는지, 그리고 PyTorch에 내장된 다양한 함수들을 배웠습니다. 
특히 사칙연산과 행렬 계산 같은 여러 함수들을 직접 사용해 봤고,
앞으로 텐서 코드를 작성할 때는 배운 함수들을 어떤 상황에 적용하면 좋을지 미리 생각하며 효율적으로 코드를 짤 수 있을 것 같습니다.